# Generated by Django 4.1.1 on 2022-09-24 12:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=25, verbose_name='Jméno hry')),
                ('gamesize', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Počet hráčů')),
                ('pok', models.BooleanField(default=True)),
                ('codex', models.BooleanField(default=True)),
                ('picking', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mapposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('taken', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='RaceDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racename', models.CharField(max_length=25)),
                ('default', models.BooleanField(default=True)),
                ('pok', models.BooleanField(default=False)),
                ('codex', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racename', models.CharField(max_length=25)),
                ('pok', models.BooleanField(default=False)),
                ('codex', models.BooleanField(default=False)),
                ('racegameorder', models.IntegerField()),
                ('in_game', models.BooleanField(default=False)),
                ('voted', models.BooleanField(default=False)),
                ('chosen', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('taken', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameorder', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('speaker', models.BooleanField(default=False)),
                ('voted', models.BooleanField(default=False)),
                ('chosenrace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.race')),
                ('game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('mappositon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.mapposition')),
                ('playername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
