# Generated by Django 4.1 on 2022-09-13 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamename',
            field=models.CharField(max_length=25, verbose_name='Jméno hry'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamesize',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Počet hráčů'),
        ),
        migrations.AlterField(
            model_name='player',
            name='playername',
            field=models.CharField(max_length=25, verbose_name='Jméno hráče'),
        ),
    ]
