# Generated by Django 4.1.1 on 2022-09-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='drafted',
            field=models.BooleanField(default=False),
        ),
    ]
